### ISSUE TITLE
Don't include the version number in the name of the distributable files

### ISSUE THREAD

**Issue by mariusGundersen** [SteveSanderson/knockout-projections#3]
The files in /dist/ should not have the version in their name, but instead as a comment at the top of the file.

**Comment by SteveSanderson** [comment]
You may be right, but could you clarify why this is the case?

The convention for scripts consumed by browsers is typically to include the version number, as it makes cache-busting trivial. For scripts consumed by CommonJS/Node.js, I appreciate that the version number is useless but since it's referenced by `main` in `package.json`, it would work fine anyway.

Right now there's a definite bug though in that `package.json` references a `main` file that doesn't even exist. I'll fix that!
